### ISSUE TITLE
Apparently code is not working

### ISSUE THREAD

**Issue by valeriadf** [vpelletier/python-hidraw#3]
I'm trying to use Your code, but I'm stuck right at the beginning.

The following test code (along with several variations):
```python
from pathlib import Path
from pyhidraw import HIDRaw


def get_devices():
    paths = sorted([f for f in Path('/dev/input').iterdir() if f.name.startswith('event')],
                   key=lambda f: int(f.name.replace('event', '')))
    devices = []
    for f in paths:
        with f.open() as fd:
            dev = HIDRaw(fd)
            name = dev.getName()
            desc = dev.getRawReportDescriptor()
        devices.append((str(f), name, desc))
    return devices


dd = get_devices()
for d in dd:
    print(d)
```
bombs with the following  error:
```
/usr/bin/python3.5 /home/valeria/MyProject/VoCore/trasmissione-telematica/Communications/Client/hidraw.py
Traceback (most recent call last):
  File "/home/valeria/MyProject/VoCore/trasmissione-telematica/Communications/Client/hidraw.py", line 18, in <module>
    dd = get_devices()
  File "/home/valeria/MyProject/VoCore/trasmissione-telematica/Communications/Client/hidraw.py", line 12, in get_devices
    name = dev.getName()
  File "/home/valeria/MyProject/VoCore/trasmissione-telematica/Communications/Client/pyhidraw.py", line 93, in getName
    self._ioctl(_HIDIOCGRAWNAME(length), name, True)
  File "/home/valeria/MyProject/VoCore/trasmissione-telematica/Communications/Client/pyhidraw.py", line 59, in _ioctl
    result = fcntl.ioctl(self._device, func, arg, mutate_flag)
OSError: [Errno 22] Invalid argument

Process finished with exit code 1
```

**Comment by vpelletier** [comment]
Hello,
The problem is that you are opening an input device (`/dev/input/event*`), not a hidraw (`/dev/hidraw*`) device (which took me a long time to spot, after first suspecting a python3 incompatibility and then succeeding to run my own quick test case), so it is the kernel complaining about the IOCTL number vs. device type mismatch.
If it is really an input device you want to open, it just happens that I wrote a quick sample code for this very syscall over in [python-ioctl-opt](/vpelletier/python-ioctl-opt)'s `README`.
